enum libraries {
    AERIAL = 'LIBRARY_AERIAL',
    CAR_RENTAL = 'LIBRARY_CAR_RENTAL',
    CRUISE = 'LIBRARY_CRUISE',
    HOTEL = 'LIBRARY_HOTEL',
    PROGRAMMING = 'LIBRARY_PROGRAMMING',
    RESTAURANT = 'LIBRARY_RESTAURANT',
    TIP = 'LIBRARY_TIP',
    TOUR = 'LIBRARY_TOUR',
    TRAIN = 'LIBRARY_TRAIN',
    TRANSFER = 'LIBRARY_TRANSFER'
}

export { libraries }
